import Header from "@/components/header/header";
import Head from "next/head";
import Image from "next/image";
import BannerImage from "assets/banner-img.png";
import Link from "next/link";
import BannerButterfly from "assets/banner-butterfly.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Kitmytrip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <section className="landing-banner section-padding bg-text_7">
          <div className="container">
            <div className="flex flex-col md:flex-row items-center">
              <div className="w-full md:w-1/2">
                <div className="banner-content">
                  <h3 className="font-normal text-fs_66 text-text_2 leading-lh_76 relative">
                    Create Better{" "}
                    <span className="font-extrabold text-fs_66">
                      Travel Content
                    </span>
                    , Faster
                    <Image
                      src={BannerButterfly}
                      className="absolute -top-16 -left-11"
                      alt="banner-img"
                    />
                  </h3>

                  <p className="font-medium text-lg leading-lh_32 text-text_3">
                    Whether you are a travel buff, an amateur travel content
                    creator or a professional <br /> travel influencer, you can
                    use kitmytrips powerful content technology platform to
                    <br /> tell incredible stories.
                  </p>
                </div>
              </div>
              <div className="w-full md:w-1/2 p-4">
                <div className="banner-img relative">
                  <Image src={BannerImage} className="" alt="banner-img" />
                  <Link
                    href={"#"}
                    className="absolute top-1/2 left-2/4 -translate-y-2/4 -translate-x-2/4"
                  >
                    <div class="h-20 w-20 bg-red-600 rounded-full flex justify-center items-center animation-pulse">
                      <svg
                        width="82"
                        height="82"
                        viewBox="0 0 82 82"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <circle cx="41" cy="41" r="41" fill="#DB105B" />
                        <path
                          d="M48.0894 42.6061C49.0911 41.8054 49.0911 40.2823 48.0894 39.4816L39.9056 32.94C38.596 31.8931 36.6569 32.8256 36.6569 34.5022V47.5855C36.6569 49.2621 38.596 50.1946 39.9056 49.1477L48.0894 42.6061Z"
                          fill="white"
                        />
                      </svg>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
